# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6af75914b961c768417ccf9c1ebca6eb68a7cb1ab23b1734c92c070ea32ad9fa53cd2b59e6f6b31bb5365905936372832150b425464a268bd71581b939fdff

test:
  secret_key_base: 8ee650fc9e5c1309ccf566ad0f69ff86d1ddbb97360332591a1f8fa3ef061a6edc96de27c6bd3c5aa798592e3af751221380c76944a9e10a1be96d0388fdef94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
